# Generated by Django 2.1.7 on 2019-03-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedmetadata',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Metadata'),
        ),
        migrations.AlterField(
            model_name='appliedmetadata',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.Sample'),
        ),
        migrations.AlterField(
            model_name='appliedmetadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.User'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.User'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.User'),
        ),
    ]
